import 'dart:ui';
import 'dart:math';

import 'package:fa_bank/ui/fa_color.dart';
import 'package:flutter/material.dart';
import 'package:flutter_money_formatter/flutter_money_formatter.dart';

class ListUtils {

  static Curve getRandomCurve() {
    return getCurve(-1);
  }

  // https://api.flutter.dev/flutter/animation/Curves-class.html
  static Curve getCurve(int id) {
    var array = [
      Curves.linear,
      Curves.decelerate,
      Curves.fastLinearToSlowEaseIn,
      Curves.ease,
      Curves.easeIn,
      Curves.easeInToLinear,
      Curves.easeInSine,
      Curves.easeInQuad,
      Curves.easeInCubic,
      Curves.easeInQuart,
      Curves.easeInQuint,
      Curves.easeInExpo,
      Curves.easeInCirc,
      Curves.easeInBack,
      Curves.easeOut,
      Curves.linearToEaseOut,
      Curves.easeOutSine,
      Curves.easeOutQuad,
      Curves.easeOutCubic,
      Curves.easeOutQuart,
      Curves.easeOutQuint,
      Curves.easeOutExpo,
      Curves.easeOutCirc,
      Curves.easeOutBack,
      Curves.easeInOut,
      Curves.easeInOutSine,
      Curves.easeInOutQuad,
      Curves.easeInOutCubic,
      Curves.easeInOutQuart,
      Curves.easeInOutQuint,
      Curves.easeInOutExpo,
      Curves.easeInOutCirc,
      Curves.easeInOutBack,
      Curves.fastOutSlowIn,
      Curves.slowMiddle,
      Curves.bounceIn,
      Curves.bounceOut,
      Curves.bounceInOut,
      Curves.elasticIn,
      Curves.elasticOut,
      Curves.elasticInOut
    ];

    return id == -1 ? array[Random().nextInt(array.length)] : array[id];
  }

  static List<String> getCountries() {
    return [
      "United States",
      "Canada",
      "Afghanistan",
      "Albania",
      "Algeria",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and/or Barbuda",
      "Argentina",
      "Armenia",
      "Aruba",
      "Australia",
      "Austria",
      "Azerbaijan",
      "Bahamas",
      "Bahrain",
      "Bangladesh",
      "Barbados",
      "Belarus",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bhutan",
      "Bolivia",
      "Bosnia and Herzegovina",
      "Botswana",
      "Bouvet Island",
      "Brazil",
      "British Indian Ocean Territory",
      "Brunei Darussalam",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Cambodia",
      "Cameroon",
      "Cape Verde",
      "Cayman Islands",
      "Central African Republic",
      "Chad",
      "Chile",
      "China",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comoros",
      "Congo",
      "Cook Islands",
      "Costa Rica",
      "Croatia (Hrvatska)",
      "Cuba",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Djibouti",
      "Dominica",
      "Dominican Republic",
      "East Timor",
      "Ecudaor",
      "Egypt",
      "El Salvador",
      "Equatorial Guinea",
      "Eritrea",
      "Estonia",
      "Ethiopia",
      "Falkland Islands (Malvinas)",
      "Faroe Islands",
      "Fiji",
      "Finland",
      "France",
      "France, Metropolitan",
      "French Guiana",
      "French Polynesia",
      "French Southern Territories",
      "Gabon",
      "Gambia",
      "Georgia",
      "Germany",
      "Ghana",
      "Gibraltar",
      "Greece",
      "Greenland",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guinea",
      "Guinea-Bissau",
      "Guyana",
      "Haiti",
      "Heard and Mc Donald Islands",
      "Honduras",
      "Hong Kong",
      "Hungary",
      "Iceland",
      "India",
      "Indonesia",
      "Iran (Islamic Republic of)",
      "Iraq",
      "Ireland",
      "Israel",
      "Italy",
      "Ivory Coast",
      "Jamaica",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kenya",
      "Kiribati",
      "Korea, Democratic People's Republic of",
      "Korea, Republic of",
      "Kosovo",
      "Kuwait",
      "Kyrgyzstan",
      "Lao People's Democratic Republic",
      "Latvia",
      "Lebanon",
      "Lesotho",
      "Liberia",
      "Libyan Arab Jamahiriya",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Macau",
      "Macedonia",
      "Madagascar",
      "Malawi",
      "Malaysia",
      "Maldives",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mauritania",
      "Mauritius",
      "Mayotte",
      "Mexico",
      "Micronesia, Federated States of",
      "Moldova, Republic of",
      "Monaco",
      "Mongolia",
      "Montserrat",
      "Morocco",
      "Mozambique",
      "Myanmar",
      "Namibia",
      "Nauru",
      "Nepal",
      "Netherlands",
      "Netherlands Antilles",
      "New Caledonia",
      "New Zealand",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Niue",
      "Norfork Island",
      "Northern Mariana Islands",
      "Norway",
      "Oman",
      "Pakistan",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Paraguay",
      "Peru",
      "Philippines",
      "Pitcairn",
      "Poland",
      "Portugal",
      "Puerto Rico",
      "Qatar",
      "Reunion",
      "Romania",
      "Russian Federation",
      "Rwanda",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Samoa",
      "San Marino",
      "Sao Tome and Principe",
      "Saudi Arabia",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Singapore",
      "Slovakia",
      "Slovenia",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Georgia South Sandwich Islands",
      "South Sudan",
      "Spain",
      "Sri Lanka",
      "St. Helena",
      "St. Pierre and Miquelon",
      "Sudan",
      "Suriname",
      "Svalbarn and Jan Mayen Islands",
      "Swaziland",
      "Sweden",
      "Switzerland",
      "Syrian Arab Republic",
      "Taiwan",
      "Tajikistan",
      "Tanzania, United Republic of",
      "Thailand",
      "Togo",
      "Tokelau",
      "Tonga",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukraine",
      "United Arab Emirates",
      "United Kingdom",
      "United States minor outlying islands",
      "Uruguay",
      "Uzbekistan",
      "Vanuatu",
      "Vatican City State",
      "Venezuela",
      "Vietnam",
      "Virigan Islands (British)",
      "Virgin Islands (U.S.)",
      "Wallis and Futuna Islands",
      "Western Sahara",
      "Yemen",
      "Yugoslavia",
      "Zaire",
      "Zambia",
      "Zimbabwe"
    ];
  }

  static List<List<String>> getSustainabilityTest() {
    return [
      [
        "Currently, your financial obligations and daily expenses (i.e. house-vehicle loan payment, personal expenses and family expenses) equal what percentage to your total income?",
        "More than 75% of the total income",
        "50-75% of the total income",
        "25-50% of the total income",
        "less than 25% of the total income"
      ],
      [
        "How would you explain your financial status?",
        "Having more Assets than Liabilities",
        "Having Assets equal to Liabilities",
        "Having less Assets than Liabilities"
      ],
      [
        "What is the key objective for your investments?",
        "The investment principal shall be secure and generate constant earning even if the earnings are low",
        "Focus on having constant earnings and can accept the lost of the investment principal to some extent",
        "Focus on having higher earnings and can accept high potential of loosing some of the investment principal",
        "Focus on having highest earnings and can accept the lost of most of the investment principal"
      ],
      [
        "You will start to be anxious about your investment assets if your portfolio drops by x%",
        "5% of less",
        "More than 5% to 10%",
        "More than 10% to 20%",
        "More than 20%"
      ],
      [
//        "Do you have any previous experience in investing in the following asset types? (select all that apply)",
        "Do you have any previous experience in investing in the following asset types?",
        "Stocks",
        "Mutual Funds",
        "Exchange Traded Fronds",
        "Bonds",
        "Derivatives",
        "Options"
      ],
      [
        "Do you have any previous experience in investing in risky and complex products?",
        "Never",
        "One-time experience",
        "Having experience of less than 1 year",
        "Having experience of more than 1 year"
      ],
      [
        "Are you trading on your own behalf?",
        "Yes",
        "No"
      ],
      [
        "Please specify your true purpose of opening an account",
        "Investment",
        "Retirement",
//        "Other (Please specify)"
        "Other"
      ],
      [
        "In the past 3 months, have you transferred investments internationally or not?",
        "Yes",
        "No"
      ],
      [
        "Are you/your spouse holding a position or having previously held a political position in any country?",
        "Yes",
        "No"
      ],
      [
        "Have you previously reported assets and liabilities accounts to government agencies as required by law or not?",
        "Yes",
        "No"
      ],
    ];
  }
}
