import 'dart:ui';
import 'dart:math';

import 'package:fa_bank/ui/fa_color.dart';
import 'package:flutter/material.dart';
import 'package:flutter_money_formatter/flutter_money_formatter.dart';

class Utils {
  static Color getColor(double d) {
    if (d > 0)
      return Colors.green;
    else if (d < 0)
      return FaColor.red[900];
    else
      return Colors.black;
  }

  static Color getColorLight(double d) {
    if (d > 0)
      return Colors.green[200];
    else if (d < 0)
      return FaColor.red[200];
    else
      return Colors.grey;
  }

  static MoneyFormatterSettings getMoneySetting(String symbol, int decimal) {
    if (symbol.toUpperCase() == 'EUR') {
      return MoneyFormatterSettings(
        symbol: '€',
        thousandSeparator: '.',
        decimalSeparator: ',',
        symbolAndNumberSeparator: ' ',
        fractionDigits: decimal,
        compactFormatType: CompactFormatType.short,
      );
    } else {
      return MoneyFormatterSettings(
        symbol: symbol.toUpperCase(),
        thousandSeparator: '.',
        decimalSeparator: ',',
        symbolAndNumberSeparator: ' ',
        fractionDigits: decimal,
        compactFormatType: CompactFormatType.short,
      );
    }
  }

  // Flutter specific, not to be copied as-is to RN
// https://api.flutter.dev/flutter/animation/Curves-class.html
  static Curve getCurve(int id) {
    var array = [
      Curves.linear,
      Curves.decelerate,
      Curves.fastLinearToSlowEaseIn,
      Curves.ease,
      Curves.easeIn,
      Curves.easeInToLinear,
      Curves.easeInSine,
      Curves.easeInQuad,
      Curves.easeInCubic,
      Curves.easeInQuart,
      Curves.easeInQuint,
      Curves.easeInExpo,
      Curves.easeInCirc,
      Curves.easeInBack,
      Curves.easeOut,
      Curves.linearToEaseOut,
      Curves.easeOutSine,
      Curves.easeOutQuad,
      Curves.easeOutCubic,
      Curves.easeOutQuart,
      Curves.easeOutQuint,
      Curves.easeOutExpo,
      Curves.easeOutCirc,
      Curves.easeOutBack,
      Curves.easeInOut,
      Curves.easeInOutSine,
      Curves.easeInOutQuad,
      Curves.easeInOutCubic,
      Curves.easeInOutQuart,
      Curves.easeInOutQuint,
      Curves.easeInOutExpo,
      Curves.easeInOutCirc,
      Curves.easeInOutBack,
      Curves.fastOutSlowIn,
      Curves.slowMiddle,
      Curves.bounceIn,
      Curves.bounceOut,
      Curves.bounceInOut,
      Curves.elasticIn,
      Curves.elasticOut,
      Curves.elasticInOut
    ];

    return id == 0 ? array[id] : array[Random().nextInt(array.length)];
  }

  //https://gist.github.com/tiveor/5444753e9919ffe74b41
  static List<String> getNationalities() {
    return [
      "Afghan",
      "Albanian",
      "Algerian",
      "American",
      "Andorran",
      "Angolan",
      "Antiguans",
      "Argentinean",
      "Armenian",
      "Australian",
      "Austrian",
      "Azerbaijani",
      "Bahamian",
      "Bahraini",
      "Bangladeshi",
      "Barbadian",
      "Barbudans",
      "Batswana",
      "Belarusian",
      "Belgian",
      "Belizean",
      "Beninese",
      "Bhutanese",
      "Bolivian",
      "Bosnian",
      "Brazilian",
      "British",
      "Bruneian",
      "Bulgarian",
      "Burkinabe",
      "Burmese",
      "Burundian",
      "Cambodian",
      "Cameroonian",
      "Canadian",
      "Cape Verdean",
      "Central African",
      "Chadian",
      "Chilean",
      "Chinese",
      "Colombian",
      "Comoran",
      "Congolese",
      "Costa Rican",
      "Croatian",
      "Cuban",
      "Cypriot",
      "Czech",
      "Danish",
      "Djibouti",
      "Dominican",
      "Dutch",
      "East Timorese",
      "Ecuadorean",
      "Egyptian",
      "Emirian",
      "Equatorial Guinean",
      "Eritrean",
      "Estonian",
      "Ethiopian",
      "Fijian",
      "Filipino",
      "Finnish",
      "French",
      "Gabonese",
      "Gambian",
      "Georgian",
      "German",
      "Ghanaian",
      "Greek",
      "Grenadian",
      "Guatemalan",
      "Guinea-Bissauan",
      "Guinean",
      "Guyanese",
      "Haitian",
      "Herzegovinian",
      "Honduran",
      "Hungarian",
      "I-Kiribati",
      "Icelander",
      "Indian",
      "Indonesian",
      "Iranian",
      "Iraqi",
      "Irish",
      "Israeli",
      "Italian",
      "Ivorian",
      "Jamaican",
      "Japanese",
      "Jordanian",
      "Kazakhstani",
      "Kenyan",
      "Kittian and Nevisian",
      "Kuwaiti",
      "Kyrgyz",
      "Laotian",
      "Latvian",
      "Lebanese",
      "Liberian",
      "Libyan",
      "Liechtensteiner",
      "Lithuanian",
      "Luxembourger",
      "Macedonian",
      "Malagasy",
      "Malawian",
      "Malaysian",
      "Maldivan",
      "Malian",
      "Maltese",
      "Marshallese",
      "Mauritanian",
      "Mauritian",
      "Mexican",
      "Micronesian",
      "Moldovan",
      "Monacan",
      "Mongolian",
      "Moroccan",
      "Mosotho",
      "Motswana",
      "Mozambican",
      "Namibian",
      "Nauruan",
      "Nepalese",
      "New Zealander",
      "Nicaraguan",
      "Nigerian",
      "Nigerien",
      "North Korean",
      "Northern Irish",
      "Norwegian",
      "Omani",
      "Pakistani",
      "Palauan",
      "Panamanian",
      "Papua New Guinean",
      "Paraguayan",
      "Peruvian",
      "Polish",
      "Portuguese",
      "Qatari",
      "Romanian",
      "Russian",
      "Rwandan",
      "Saint Lucian",
      "Salvadoran",
      "Samoan",
      "San Marinese",
      "Sao Tomean",
      "Saudi",
      "Scottish",
      "Senegalese",
      "Serbian",
      "Seychellois",
      "Sierra Leonean",
      "Singaporean",
      "Slovakian",
      "Slovenian",
      "Solomon Islander",
      "Somali",
      "South African",
      "South Korean",
      "Spanish",
      "Sri Lankan",
      "Sudanese",
      "Surinamer",
      "Swazi",
      "Swedish",
      "Swiss",
      "Syrian",
      "Taiwanese",
      "Tajik",
      "Tanzanian",
      "Thai",
      "Togolese",
      "Tongan",
      "Trinidadian or Tobagonian",
      "Tunisian",
      "Turkish",
      "Tuvaluan",
      "Ugandan",
      "Ukrainian",
      "Uruguayan",
      "Uzbekistani",
      "Venezuelan",
      "Vietnamese",
      "Welsh",
      "Yemenite",
      "Zambian",
      "Zimbabwean"
    ];
  }
}
